### ISSUE TITLE
收不到推送需要修改AndroidManifest的application标签name

### ISSUE THREAD

**Issue by caiyoufei** [jiangyubao/flutter_umpush#1]
折腾了一下午，一直收不到推送，结果发现是因为application的name没有使用com.github.flutterumpush.UmengApplication
改为这个就可以了

**Comment by caiyoufei** [comment]
建议楼主标一下，因为UmengApplication点不过去，所以使用时很可能不知道这个问题

**Comment by jiangyubao** [comment]
这个是自带demo的，你先把demo跑通

**Comment by jiangyubao** [comment]
备注：application的name修改为com.github.flutterumpush.UmengApplication，否则无法通过
