### ISSUE TITLE
<meta-data> appid为纯数字会取值错误

### ISSUE THREAD

**Issue by luzhenxing** [jiangyubao/flutter_umpush#2]
小米push推送无法调通：原因是XM_APP_ID、XM_APP_KEY是由纯数字组成，这个在使用```appInfo.metaData.get()```这个方法取出来的值是**浮点型（如：1.23456）**，所以后续注册会失败

**Comment by jiangyubao** [comment]
配置的XM_APP_ID的时候，凡是数字，都要加\0

**Comment by jiangyubao** [comment]
配置的XM_APP_ID的时候，凡是数字，都要加\0
